<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.jdbc.support.DatabaseStartupValidatorTests" tests="7" skipped="0" failures="0" errors="0" timestamp="2021-04-26T07:39:59" hostname="wangweilideMacBook-Pro.local" time="4.034">
  <properties/>
  <testcase name="shouldCallValidatonTwiceInCaseOfException()" classname="org.springframework.jdbc.support.DatabaseStartupValidatorTests" time="1.007"/>
  <testcase name="shouldCallValidatonTwiceWhenNotValid()" classname="org.springframework.jdbc.support.DatabaseStartupValidatorTests" time="1.002"/>
  <testcase name="shouldExecuteValidatonTwiceOnError()" classname="org.springframework.jdbc.support.DatabaseStartupValidatorTests" time="1.009"/>
  <testcase name="useValidationQueryInsteadOfIsValid()" classname="org.springframework.jdbc.support.DatabaseStartupValidatorTests" time="0.003"/>
  <testcase name="exceededTimeoutThrowsException()" classname="org.springframework.jdbc.support.DatabaseStartupValidatorTests" time="1.007"/>
  <testcase name="shouldUseJdbc4IsValidByDefault()" classname="org.springframework.jdbc.support.DatabaseStartupValidatorTests" time="0.003"/>
  <testcase name="properSetupForDataSource()" classname="org.springframework.jdbc.support.DatabaseStartupValidatorTests" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
