<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.test.web.servlet.samples.standalone.ExceptionHandlerTests$RestTests" tests="5" skipped="0" failures="0" errors="0" timestamp="2021-05-01T09:42:54" hostname="wangweilideMBP.lan" time="0.123">
  <properties/>
  <testcase name="globalRestPersonControllerExceptionHandlerTakesPrecedenceOverGlobalExceptionHandler()" classname="org.springframework.test.web.servlet.samples.standalone.ExceptionHandlerTests$RestTests" time="0.032"/>
  <testcase name="noException()" classname="org.springframework.test.web.servlet.samples.standalone.ExceptionHandlerTests$RestTests" time="0.019"/>
  <testcase name="localExceptionHandlerMethod()" classname="org.springframework.test.web.servlet.samples.standalone.ExceptionHandlerTests$RestTests" time="0.022"/>
  <testcase name="globalExceptionHandlerMethod()" classname="org.springframework.test.web.servlet.samples.standalone.ExceptionHandlerTests$RestTests" time="0.025"/>
  <testcase name="noHandlerFound()" classname="org.springframework.test.web.servlet.samples.standalone.ExceptionHandlerTests$RestTests" time="0.025"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
