<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.test.web.servlet.samples.client.standalone.ExceptionHandlerTests$RestTests" tests="5" skipped="0" failures="0" errors="0" timestamp="2021-05-09T12:42:10" hostname="wangweilidembp" time="0.078">
  <properties/>
  <testcase name="globalRestPersonControllerExceptionHandlerTakesPrecedenceOverGlobalExceptionHandler()" classname="org.springframework.test.web.servlet.samples.client.standalone.ExceptionHandlerTests$RestTests" time="0.018"/>
  <testcase name="noException()" classname="org.springframework.test.web.servlet.samples.client.standalone.ExceptionHandlerTests$RestTests" time="0.015"/>
  <testcase name="localExceptionHandlerMethod()" classname="org.springframework.test.web.servlet.samples.client.standalone.ExceptionHandlerTests$RestTests" time="0.017"/>
  <testcase name="globalExceptionHandlerMethod()" classname="org.springframework.test.web.servlet.samples.client.standalone.ExceptionHandlerTests$RestTests" time="0.015"/>
  <testcase name="noHandlerFound()" classname="org.springframework.test.web.servlet.samples.client.standalone.ExceptionHandlerTests$RestTests" time="0.013"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
